name: Documentation
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install ".[all]"
      - name: Build docs
        run: |
          pdoc --html \
            --config="git_link_template=\"https://github.com/dhimmel/pubmedpy/blob/{commit}/{path}#L{start_line}-L{end_line}\"" \
            --output-dir=docs \
            pubmedpy
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'  && !github.event.repository.fork
        uses: peaceiris/actions-gh-pages@v3
        env:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: docs/pubmedpy
          allow_empty_commit: false
